#!/bin/bash

mkdir -p /tmp/edge-config

defaults write /tmp/edge-config/com.microsoft.edge HideFirstRunExperience -bool true
defaults write /tmp/edge-config/com.microsoft.edge SearchInSidebarEnabled -int 2
defaults write /tmp/edge-config/com.microsoft.edge HubsSidebarEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge ReadAloudEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge DiagnosticData -bool false
defaults write /tmp/edge-config/com.microsoft.edge PinBrowserEssentialsToolbarButton -bool false
defaults write /tmp/edge-config/com.microsoft.edge EdgeCollectionsEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge FavoritesBarEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge PersonalizationReportingEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge SplitScreenEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge ImplicitSignInEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge GuidedSwitchEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge EdgeDefaultProfileEnabled -string "Default"
defaults write /tmp/edge-config/com.microsoft.edge BrowserSignin -bool true
defaults write /tmp/edge-config/com.microsoft.edge ShowMicrosoftRewards -bool false
defaults write /tmp/edge-config/com.microsoft.edge AutoImportAtFirstRun -int 4
defaults write /tmp/edge-config/com.microsoft.edge EdgeWorkspacesEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge EdgeWalletCheckoutEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge EdgeWalletEtreeEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge BuiltInDnsClientEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge AADWebSiteSSOUsingThisProfileEnabled -bool true
defaults write /tmp/edge-config/com.microsoft.edge AccessibilityImageLabelsEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge AddressBarMicrosoftSearchInBingProviderEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge AllowGamesMenu -bool false
defaults write /tmp/edge-config/com.microsoft.edge AutomaticHttpsDefault -int 2
defaults write /tmp/edge-config/com.microsoft.edge BrowserAddProfileEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge BrowserGuestModeEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge ComposeInlineEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge ConfigureOnPremisesAccountAutoSignIn -bool false
defaults write /tmp/edge-config/com.microsoft.edge ConfigureOnlineTextToSpeech -bool false
defaults write /tmp/edge-config/com.microsoft.edge ConfigureShare -bool false
defaults write /tmp/edge-config/com.microsoft.edge DefaultBrowserSettingsCampaignEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge Edge3PSerpTelemetryEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge EdgeEDropEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge SyncDisabled -bool true
defaults write /tmp/edge-config/com.microsoft.edge WalletDonationEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge NonRemovableProfileEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge ImportOnEachLaunch -bool false
defaults write /tmp/edge-config/com.microsoft.edge InAppSupportEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge LocalBrowserDataShareEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge LiveCaptionsAllowed -bool false
defaults write /tmp/edge-config/com.microsoft.edge MSAWebSiteSSOUsingThisProfileAllowed -bool false
defaults write /tmp/edge-config/com.microsoft.edge MicrosoftEdgeInsiderPromotionEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge MicrosoftEditorSynonymsEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge MicrosoftEditorProofingEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge RelatedWebsiteSetsEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge PaymentMethodQueryEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge PinningWizardAllowed -bool false
defaults write /tmp/edge-config/com.microsoft.edge PromotionalTabsEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge QuickSearchShowMiniMenu -bool false
defaults write /tmp/edge-config/com.microsoft.edge QuickViewOfficeFilesEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge RelatedMatchesCloudServiceEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge RemoteDebuggingAllowed -bool false
defaults write /tmp/edge-config/com.microsoft.edge ResolveNavigationErrorsUseWebService -bool false
defaults write /tmp/edge-config/com.microsoft.edge RoamingProfileSupportEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge SearchForImageEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge SearchFiltersEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge SearchbarAllowed -bool false
defaults write /tmp/edge-config/com.microsoft.edge SearchbarIsEnabledOnStartup -bool false
defaults write /tmp/edge-config/com.microsoft.edge SharedLinksEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge ShowAcrobatSubscriptionButton -bool false
defaults write /tmp/edge-config/com.microsoft.edge ShowOfficeShortcutInFavoritesBar -bool false
defaults write /tmp/edge-config/com.microsoft.edge ShowRecommendationsEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge SpeechRecognitionEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge StandaloneHubsSidebarEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge TabServicesEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge TextPredictionEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge UploadFromPhoneEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge VisualSearchEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge NewTabPageSearchBox -string "redirect"
defaults write /tmp/edge-config/com.microsoft.edge PasswordGeneratorEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge PasswordManagerEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge PasswordMonitorAllowed -bool false
defaults write /tmp/edge-config/com.microsoft.edge PasswordProtectionWarningTrigger -bool false
defaults write /tmp/edge-config/com.microsoft.edge AlternateErrorPagesEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge AskBeforeCloseEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge AutofillAddressEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge AutofillCreditCardEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge AutofillMembershipsEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge AADWebSSOAllowed -bool true
defaults write /tmp/edge-config/com.microsoft.edge AIGenThemesEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge AccessCodeCastEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge AdditionalDnsQueryTypesEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge AdsTransparencyEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge EdgeAdminCenterEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge BingAdsSuppression -bool true
defaults write /tmp/edge-config/com.microsoft.edge ConfigureDoNotTrack -bool true
defaults write /tmp/edge-config/com.microsoft.edge EdgeAssetDeliveryServiceEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge EdgeShoppingAssistantEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge ExperimentationAndConfigurationServiceControl -bool false
defaults write /tmp/edge-config/com.microsoft.edge NetworkPredictionOptions -bool false
defaults write /tmp/edge-config/com.microsoft.edge UserFeedbackAllowed -bool false
defaults write /tmp/edge-config/com.microsoft.edge WebWidgetAllowed -bool false
defaults write /tmp/edge-config/com.microsoft.edge TyposquattingCheckerEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge TrackingPrevention -int 3
defaults write /tmp/edge-config/com.microsoft.edge SigninInterceptionEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge SideSearchEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge ShowPDFDefaultRecommendationsEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge ShowHomeButton -bool false
defaults write /tmp/edge-config/com.microsoft.edge ShoppingListEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge SafeBrowsingSurveysEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge SafeBrowsingDeepScanningEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge SafeBrowsingProxiedRealTimeChecksAllowed -bool false
defaults write /tmp/edge-config/com.microsoft.edge PasswordDismissCompromisedAlertEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge MAMEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge HighEfficiencyModeEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge EdgeManagementEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge DesktopSharingHubEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge CopilotPageContextEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge ProactiveAuthWorkflowEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge CopilotPageContext -bool false
defaults write /tmp/edge-config/com.microsoft.edge NewTabPageContentEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge NewTabPageAppLauncherEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge NewTabPageBingChatEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge NewTabPageQuickLinksEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge QRCodeGeneratorEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge TranslateEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge SpotlightExperiencesAndRecommendationsEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge ApplicationGuardFavoritesSyncEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge ApplicationGuardTrafficIdentificationEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge WebToBrowserSignInEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge SeamlessWebToBrowserSignInEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge EdgeAutofillMlEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge GenAILocalFoundationalModelSettings -bool true
defaults write /tmp/edge-config/com.microsoft.edge PersonalizeTopSitesInCustomizeSidebarEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge ExtensionsPerformanceDetectorEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge PerformanceDetectorEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge EdgeEntraCopilotPageContext -bool false
defaults write /tmp/edge-config/com.microsoft.edge MouseGestureEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge DisableScreenshots -bool false
defaults write /tmp/edge-config/com.microsoft.edge WebCaptureEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge SpellcheckEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge AddressBarWorkSearchResultsEnabled -bool false
defaults write /tmp/edge-config/com.microsoft.edge ScarewareBlockerProtectionEnabled -bool false

echo "Expect to be prompted to enter your password by sudo."
sudo mv /tmp/edge-config/com.microsoft.edge.plist /Library/Managed\ Preferences/
sudo chown root:wheel /Library/Managed\ Preferences/com.microsoft.edge.plist
sudo chmod 644 /Library/Managed\ Preferences/com.microsoft.edge.plist
rm -rf /tmp/edge-config

echo "Edge has been debloated. Delete /Library/Managed Preferences/com.microsoft.edge.plist to revert."